name: Release

on:
  push:
    branches-ignore:
      - develop

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://registry.npmjs.org/"
          scope: "@opengovsg"

      - name: Install Dependencies
        run: |
          pnpm i --frozen-lockfile
          npm install -g @microsoft/api-documenter
          npm install -g @microsoft/api-extractor

      - name: Check API report
        run: pnpm ci:report

      - name: Generate documentation
        run: pnpm build:docs

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/.vitepress/dist
