name: Release

on:
  push:
    tags:
      - "*/v*"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://registry.npmjs.org/"
          scope: "@opengovsg"

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: 🔨 Build
        run: pnpm build

      - name: Publish to NPM
        run: pnpm -r publish --no-git-checks --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://npm.pkg.github.com/"
          scope: "@opengovsg"

      - name: Publish to NPM
        run: pnpm -r publish --no-git-checks --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
